(source "melpa" "http://melpa.milkbox.net/packages/")
(source gnu)
(source marmalade)
(source org)

(depends-on "ack-and-a-half")
(depends-on "auctex")
(depends-on "auto-complete")
(depends-on "cask")
(depends-on "company")
(depends-on "dash")
(depends-on "elpy")
(depends-on "epl")
(depends-on "f")
(depends-on "flx")
(depends-on "flx-ido")
(depends-on "flycheck-cask")
(depends-on "flycheck-google-cpplint")
(depends-on "google-c-style")
(depends-on "highlight-indentation")
(depends-on "let-alist")
(depends-on "openwith")
(depends-on "pallet")
(depends-on "pkg-info")
(depends-on "pyvenv")
(depends-on "s")
(depends-on "shut-up")
(depends-on "yasnippet")
